import './AboutPage.css';

export default function AboutPage() {
  return (
    <div className="about-page page-container">
      <div className="about-inner">
        <div className="about-icon" aria-hidden="true">
          <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
            <path d="M9 12l2 2 4-4"/>
          </svg>
        </div>

        <h1 className="about-title">About AI Verify</h1>
        <p className="about-lead">
          AI Verify is a standards-first image verification tool that helps you understand the likely
          origin of an image — whether it was captured by a camera or generated by AI.
        </p>

        <div className="about-section">
          <h2>How it works</h2>
          <ol className="about-steps">
            <li>
              <strong>Provenance check</strong> — We first inspect Content Credentials (C2PA) embedded in the image. If the image has a verified chain of custody, that is the most reliable evidence.
            </li>
            <li>
              <strong>Metadata inspection</strong> — File metadata (EXIF) is read for camera model, software, creation date, and dimensions.
            </li>
            <li>
              <strong>Watermark signals</strong> — We check for embedded digital watermarks or signals from known AI providers.
            </li>
            <li>
              <strong>Visual AI analysis</strong> — Only when provenance and metadata are inconclusive do we run a visual AI detector, which examines statistical patterns in the image.
            </li>
          </ol>
        </div>

        <div className="about-section">
          <h2>Important limitations</h2>
          <ul className="about-limits">
            <li>No automated system can guarantee 100% accuracy in detecting AI-generated content.</li>
            <li>Absence of metadata or watermarks <em>does not</em> confirm AI generation.</li>
            <li>Sophisticated editing can remove or spoof metadata.</li>
            <li>Results should be one input among multiple forms of evidence.</li>
          </ul>
        </div>

        <div className="about-section">
          <h2>Privacy</h2>
          <p>
            Images are processed locally in your browser and are not uploaded to or stored on any external server.
            Verification history is stored only in your browser's local storage.
          </p>
        </div>
      </div>
    </div>
  );
}
